In [1]:
# 统计含有inf的距离矩阵的个数
import os
import numpy as np

dir_path = "/home/wngys/lab/DeepFold/distance_matrix/distance_matrix_inf/"  # 3419
# dir_path = "/home/wngys/lab/DeepFold/distance_matrix/distance_matrix_mine/"  # 0
# dir_path = "/home/wngys/lab/DeepFold/distance_matrix/distance_matrix_modified/" # 214

inf_List = []
for child_path in os.listdir(dir_path):
    child_path = os.path.join(dir_path, child_path)
    M_2 = np.load(child_path, allow_pickle=True)
    inf_n = np.sum(np.isinf(M_2))
    if inf_n != 0:
        # print(child_path, inf_n)
        inf_List.append((child_path, inf_n))

In [3]:
print(len(inf_List))
print(inf_List[:10])

0
[]


In [1]:
# mine和modified的矩阵对比
import numpy as np

IDList = np.load("/home/wngys/lab/DeepFold/protein_infor/IDArray.npy", allow_pickle=True).tolist()

shapeList = []
infList = []
nanList = []
diffList = []

dir_path1 = "/home/wngys/lab/DeepFold/distance_matrix/distance_matrix_mine/"
dir_path2 = "/home/wngys/lab/DeepFold/distance_matrix/distance_matrix_modified/"
# dir_path2 = "/home/wngys/lab/DeepFold/distance_matrix/distance_matrix_inf/"

printError = False
recordError = True
f_w = open("/home/wngys/lab/DeepFold/distance_matrix_infor/errorLog.txt", "w")

i = 0
for mat_id in IDList:
    i = i + 1
    if i % 100 == 0:
        print(i)
    # if i > 500:
    #     break

    dist_mat_path1 = dir_path1 + mat_id + ".npy"
    dist_mat_path2 = dir_path2 + mat_id + ".npy"

    dist_mat1 = np.load(dist_mat_path1, allow_pickle=True)
    dist_mat2 = np.load(dist_mat_path2, allow_pickle=True)

    shape_flag = False
    inf_flag = False
    nan_flag = False    

    if not ((dist_mat1.shape[0] == dist_mat2.shape[0]) and (dist_mat1.shape[1] == dist_mat2.shape[1])):
        if printError:
            print(mat_id, "shapes are different:", dist_mat1.shape, ",", dist_mat2.shape)
        if recordError:
            f_w.write(mat_id + " shapes are different: " + str(dist_mat1.shape) + ", " + str(dist_mat2.shape) + "\n")
        shape_flag = True
        shapeList.append(mat_id)
    
    if (np.sum(np.isinf(dist_mat1)) != 0) or (np.sum(np.isinf(dist_mat2)) != 0):
        if printError:
            print(mat_id, "have inf:", np.sum(np.isinf(dist_mat1)), ",", np.sum(np.isinf(dist_mat2)))
        if recordError:
            f_w.write(mat_id + " have inf: " + str(np.sum(np.isinf(dist_mat1))) + ", " + str(np.sum(np.isinf(dist_mat2))) + "\n")
        inf_flag = True
        infList.append(mat_id)
    
    if (np.sum(np.isnan(dist_mat1)) != 0) or (np.sum(np.isnan(dist_mat2)) != 0):
        if printError:
            print(mat_id, "have nan:", np.sum(np.isnan(dist_mat1)), ",", np.sum(np.isnan(dist_mat2)))
        if recordError:
            f_w.write(mat_id + " have nan: " + str(np.sum(np.isnan(dist_mat1))) + ", " + str(np.sum(np.isnan(dist_mat2))) + "\n")
        nan_flag = True
        nanList.append(mat_id)
    
    if not (shape_flag or inf_flag or nan_flag):
        diff = np.sum(np.abs(dist_mat1 - dist_mat2))
        num = dist_mat1.shape[0] * dist_mat1.shape[0]
        mean_diff  = diff / num
        if mean_diff > 0.1:
            if printError:
                print(mat_id, "difference too large:", diff, "|", num, "|", mean_diff)
            if recordError:
                f_w.write(mat_id + " difference too large: " + str(diff) + " | " + str(num) + " | " + str(mean_diff) + "\n")
            diffList.append(mat_id)

f_w.close()

100
200
300
400
500
600
700
800
900
1000
1100
1200
1300
1400
1500
1600
1700
1800
1900
2000
2100
2200
2300
2400
2500
2600
2700
2800
2900
3000
3100
3200
3300
3400
3500
3600
3700
3800
3900
4000
4100
4200
4300
4400
4500
4600
4700
4800
4900
5000
5100
5200
5300
5400
5500
5600
5700
5800
5900
6000
6100
6200
6300
6400
6500
6600
6700
6800
6900
7000
7100
7200
7300
7400
7500
7600
7700
7800
7900
8000
8100
8200
8300
8400
8500
8600
8700
8800
8900
9000
9100
9200
9300
9400
9500
9600
9700
9800
9900
10000
10100
10200
10300
10400
10500
10600
10700
10800
10900
11000
11100
11200
11300
11400
11500
11600
11700
11800
11900
12000
12100
12200
12300
12400
12500
12600
12700
12800
12900
13000
13100
13200
13300
13400
13500
13600
13700
13800
13900
14000
14100
14200


In [2]:
print(len(shapeList))
print(len(infList))
print(len(nanList))
print(len(diffList))

276
214
0
3


In [17]:
print(shapeList[:10])
print(infList[:10])
print(diffList)

['d1e25a_', 'd2e2ra_', 'd2y8ga_', 'd2c7na1', 'd1b89a_', 'd2ce7a1', 'd1gvnb_', 'd1gvza_', 'd3gv3a_', 'd1gvna_']
['d2e2ra_', 'd2y8ga_', 'd2c7na1', 'd1b89a_', 'd2ce7a1', 'd1gvnb_', 'd3gv3a_', 'd1gvna_', 'd1ohua_', 'd1ohea2']
['d4hbqa1', 'd1tqga1', 'd4g38a1']


In [3]:
M_2 = np.load("/home/wngys/lab/DeepFold/distance_matrix/distance_matrix_mine/d4hbqa1.npy", allow_pickle=True)
print(M_2.shape)
print(M_2)

(90, 90)
[[ 0.          3.81569666  6.05150039 ... 27.9338945  30.9155966
  33.58237212]
 [ 3.81569666  0.          3.81682564 ... 25.45058323 28.46188476
  31.3568833 ]
 [ 6.05150039  3.81682564  0.         ... 26.10880903 28.79958524
  31.88928334]
 ...
 [27.9338945  25.45058323 26.10880903 ...  0.          3.7970266
   6.49436379]
 [30.9155966  28.46188476 28.79958524 ...  3.7970266   0.
   3.78376453]
 [33.58237212 31.3568833  31.88928334 ...  6.49436379  3.78376453
   0.        ]]


In [4]:
M_3 = np.load("/home/wngys/lab/DeepFold/distance_matrix/distance_matrix_modified/d4hbqa1.npy", allow_pickle=True)
print(M_3.shape)
print(M_3)

(90, 90)
[[ 0.          3.80102755  6.48484342 ... 28.30272775 31.37582069
  34.06197184]
 [ 3.80102755  0.          3.81682524 ... 25.45058462 28.46188583
  31.35688442]
 [ 6.48484342  3.81682524  0.         ... 26.10880876 28.79958469
  31.88928278]
 ...
 [28.30272775 25.45058462 26.10880876 ...  0.          3.79702626
   6.49436341]
 [31.37582069 28.46188583 28.79958469 ...  3.79702626  0.
   3.78376435]
 [34.06197184 31.35688442 31.88928278 ...  6.49436341  3.78376435
   0.        ]]


In [18]:
np.abs(M_2-M_3)

array([[0.00000000e+00, 1.46691094e-02, 4.33343030e-01, ...,
        3.68833249e-01, 4.60224094e-01, 4.79599720e-01],
       [1.46691094e-02, 0.00000000e+00, 3.99778607e-07, ...,
        1.38724725e-06, 1.07565450e-06, 1.12739614e-06],
       [4.33343030e-01, 3.99778607e-07, 0.00000000e+00, ...,
        2.69955247e-07, 5.54997104e-07, 5.61699338e-07],
       ...,
       [3.68833249e-01, 1.38724725e-06, 2.69955247e-07, ...,
        0.00000000e+00, 3.42960178e-07, 3.81042468e-07],
       [4.60224094e-01, 1.07565450e-06, 5.54997104e-07, ...,
        3.42960178e-07, 0.00000000e+00, 1.80570202e-07],
       [4.79599720e-01, 1.12739614e-06, 5.61699338e-07, ...,
        3.81042468e-07, 1.80570202e-07, 0.00000000e+00]])

In [16]:
np.max(np.abs(M_2-M_3))

5.275202881373677

In [19]:
np.abs(M_2-M_3) == np.max(np.abs(M_2-M_3))

array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False]])

In [23]:
M_2[(np.abs(M_2-M_3) == np.max(np.abs(M_2-M_3)))]

array([5.41091711, 5.41091711])

In [21]:
np.sum(M_2 * (np.abs(M_2-M_3) == np.max(np.abs(M_2-M_3))))

10.821834225305798

In [22]:
np.sum(M_3 * (np.abs(M_2-M_3) == np.max(np.abs(M_2-M_3))))

21.372239988053153

In [1]:
import numpy as np

In [2]:
f_w = open("errorLog.txt", "w")

In [5]:
dist_mat1 = np.load("/home/wngys/lab/DeepFold/distance_matrix/distance_matrix_modified/d4e29a_.npy", allow_pickle=True)
dist_mat2 = np.load("/home/wngys/lab/DeepFold/distance_matrix/distance_matrix_modified/d4e29a_.npy", allow_pickle=True)