In [1]:
# 获取矩阵每一项的倒数所组成的矩阵
import warnings
warnings.filterwarnings('ignore')
import numpy as np
import copy

matIDList = np.load("/home/wngys/lab/DeepFold/protein_infor/IDArray.npy", allow_pickle=True).tolist()

dir_path1 = "/home/wngys/lab/DeepFold/distance_matrix/distance_matrix_mine/"
dir_path2 = "/home/wngys/lab/DeepFold/distance_matrix_r/distance_matrix_mine_r/"

resEndList = []

for mat_id in matIDList:
    dist_mat_path1 = dir_path1 + mat_id + ".npy"
    dist_mat_path2 = dir_path2 + mat_id + ".npy"

    dist_mat1 = np.load(dist_mat_path1, allow_pickle=True)
    dist_mat2 = 1.0 / dist_mat1

    inf_position = np.isinf(dist_mat2)
    dist_mat2_temp = copy.deepcopy(dist_mat2)
    dist_mat2_temp[inf_position] = 0
    dist_mat2[inf_position] = np.max(dist_mat2_temp) * 1.2
    
    np.save(dist_mat_path2, dist_mat2)

In [4]:
# 测试：加载举例矩阵
M_2 = np.load("/home/wngys/lab/DeepFold/distance_matrix/distance_matrix_mine/d1a0tp_.npy", allow_pickle=True)
print(M_2.shape)
print(M_2)

(413, 413)
[[ 0.          3.80618838  7.1816952  ... 24.6348408  21.46587305
  17.99335494]
 [ 3.80618838  0.          3.77360385 ... 22.964154   19.92721953
  16.69197382]
 [ 7.1816952   3.77360385  0.         ... 19.81995189 16.92678593
  13.94977541]
 ...
 [24.6348408  22.964154   19.81995189 ...  0.          3.70305212
   6.84151701]
 [21.46587305 19.92721953 16.92678593 ...  3.70305212  0.
   3.77722279]
 [17.99335494 16.69197382 13.94977541 ...  6.84151701  3.77722279
   0.        ]]


In [3]:
M_3 = np.load("/home/wngys/lab/DeepFold/distance_matrix_r/distance_matrix_mine_r/d1a0tp_.npy", allow_pickle=True)
print(M_3.shape)
print(M_3)

(413, 413)
[[0.32405701 0.26273003 0.13924289 ... 0.04059292 0.04658557 0.05557607]
 [0.26273003 0.32405701 0.26499867 ... 0.04354613 0.05018262 0.05990903]
 [0.13924289 0.26499867 0.32405701 ... 0.05045421 0.05907796 0.07168574]
 ...
 [0.04059292 0.04354613 0.05045421 ... 0.32405701 0.27004751 0.14616641]
 [0.04658557 0.05018262 0.05907796 ... 0.27004751 0.32405701 0.26474478]
 [0.05557607 0.05990903 0.07168574 ... 0.14616641 0.26474478 0.32405701]]
